# Generated by Django 5.0.6 on 2024-07-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
