# Generated by Django 5.0.6 on 2024-07-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_carmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
