# Generated by Django 5.0.6 on 2024-07-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_carmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='image',
        ),
    ]
