# Generated by Django 5.0.6 on 2024-07-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
