# Generated by Django 5.0.6 on 2024-07-14 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0013_carmodel_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='buyer',
        ),
    ]
