# Generated by Django 5.0.6 on 2024-07-03 04:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(help_text='enter a valid mail address', max_length=254)),
                ('phone', models.IntegerField(help_text='enter a phone number maximu 12 digits', max_length=12)),
                ('insturment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_Realease_Date', models.DateField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Album_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_person.musician')),
            ],
        ),
    ]
