# Generated by Django 5.0.6 on 2024-07-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albummodel',
            old_name='Album_name',
            new_name='musician',
        ),
        migrations.AddField(
            model_name='albummodel',
            name='album_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musician',
            name='phone',
            field=models.CharField(help_text='enter a phone number maximum 12 digits', max_length=12),
        ),
    ]
