# Generated by Django 5.0.6 on 2024-07-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('Task_Assign_Date', models.DateField()),
                ('is_Completed', models.BooleanField(default=False)),
            ],
        ),
    ]
