# Generated by Django 5.0.6 on 2024-07-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_remove_categorymodel_relation'),
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='Catagories',
            field=models.ManyToManyField(to='category_app.categorymodel'),
        ),
    ]
