# Generated by Django 5.0.6 on 2024-07-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_taskmodel_catagories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
