# Generated by Django 5.0.6 on 2024-07-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to='files/')),
                ('generic_ip_address_field', models.GenericIPAddressField()),
                ('slug_field', models.SlugField()),
            ],
        ),
    ]
