# Generated by Django 5.0.6 on 2024-06-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_student_father_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='roll',
        ),
    ]
