# Generated by Django 5.0.6 on 2024-07-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_remove_categorymodel_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='Category_Name',
            field=models.CharField(max_length=100),
        ),
    ]
